trigger:
- master

pool:
  vmImage: 'windows-2019'

name: 1.0.$(Build.BuildId)

variables:
  solution: '*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  displayName: 'Preparing SonarCloud Analysis'
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'atc-net'
    scannerMode: 'MSBuild'
    projectKey: 'atc-net_atc-autoformatter'
    projectName: '$(Build.Repository.Name)'

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.4.0'
  inputs:
    versionSpec: 5.4.0

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'

- task: VsixToolsUpdateVersion@2
  displayName: 'Set Vsix Version'
  inputs:
    FileName: src/Atc.AutoFormatter/source.extension.vsixmanifest
    VersionNumber: '$(build.buildnumber)'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Test solution'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    codeCoverageEnabled: true

- task: SonarCloudAnalyze@1
  displayName: 'Run Code Analysis and Publish Quality Gate Result'

- task: CopyFiles@2
  displayName: 'Copy artifacts'
  inputs:
    contents: |
      **/*.vsix
      publish-manifest.json
      README.md
      src/Atc.AutoFormatter/Resources/*.png
    targetFolder: $(Build.ArtifactStagingDirectory)
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: drop
